### PR TITLE
Update models.py

### PR DESCRIPTION
**Pull request by arthur-s**
in my project i use another file storage. Why not to use storage, defined in settings.DEFAULT_FILE_STORAGE?

### CODE REVIEW

**Comment by mbraak** [comment]
Django-file-form uses the django filesystem-storage to temporarily store the uploaded files. I think the filesystem storage is best for this because the files are stored temporarily.

**Comment by arthur-s** [comment]
can you look at my version? i made changes. I'm new in github, how can i merge my edits with yours, if you like?
https://github.com/arthur-s/django-file-form/blob/master/django_file_form/models.py

**Comment by mbraak** [comment]
I will have a look at your version.

What kind of file storage are you using?

**Comment by arthur-s** [comment]
I decided to make very very simple custom storage for my needs. In my version i made little edits, added two lines in conf.py
```python
STORAGE = getattr(settings, 'FILE_FORM_STORAGE', 'django.core.files.storage.FileSystemStorage')
STORAGE_KWARGS = getattr(settings, 'FILE_FORM_STORAGE_KWARGS', {'location': settings.MEDIA_ROOT})
```
and in models.py
```python
from django.utils.functional import LazyObject
from django.utils.module_loading import import_string
from . import conf

...
def get_storage_class():
    return import_string(conf.STORAGE)

class Storage(LazyObject):
    def _setup(self):
        self._wrapped = get_storage_class()()
...
# fs = FileSystemStorage(location=settings.MEDIA_ROOT)
    fs = Storage(**conf.STORAGE_KWARGS)
```

**Comment by mbraak** [comment]
I think this change is very specific for your situation. I think the best solution is that you use your own fork of django-file-form.

**Comment by arthur-s** [comment]
okay

**Pull request closed without merging**
