### PR TITLE
make backends configurable

### PR DESCRIPTION
**Pull request by tleguijt**
I'm using django-file-form in one of our projects and we need a custom FTP upload backend for this.
To utilize this I've made the backends pluggable/configurable.

### CODE REVIEW

**Comment by mbraak** [comment]
Thanks! This sounds like a good idea. I will have a look at it.

**Comment by mbraak** [comment]
Hello Tim,

I changed some code to fix the unit tests: https://github.com/mbraak/django-file-form/commits/tleguijt-feature/configurable

It is possible that these changes break your project. Could you please check if everything still works?

Greetings,
Marco

**Comment by tleguijt** [comment]
Perfect, these changes don't break my project.
Thanks for the quick response!

**Comment by mbraak** [comment]
Thanks! This is now merged.

**Pull request merged**
