### PR TITLE
Drop area

### PR DESCRIPTION
**Pull request by mbraak**
Based on #270 

The drop area is turned on by default. Set `supportDropArea` to false to turn it on:

```js
initUploadFields(
  document.getElementById("example-form"),
  {
    supportDropArea: false
  }
);
```

### CODE REVIEW

**Comment by BoPeng** [comment]
Thanks for improving my PR but I have to say I like my original implementation that re-uses the files list box as drop area a lot better than your implementation. When you "drop" something into an area, you expect the dropped items to appear in that area, right? IMHO, my implementation is also aesthetically a bit cleaner in that it has one less UI element and the initial hint is gone as soon as users uses the droparea (and the hint is no longer needed). This is of course my personal preference but all the top google searches I have seen when I search "file drop area" have dropped images displayed in the drop area (e.g. [here](https://www.smashingmagazine.com/2018/01/drag-drop-file-uploader-vanilla-js/), [here](https://github.com/rogeriotaques/dropar)).

**Comment by mbraak** [comment]
I'll try out a version that re-uses the file list.

**Comment by BoPeng** [comment]
Thanks. That implementation will also turn the `supportDropArea: true` option to an addition of

```
.dff-files {
  min-height: 2em;
}
```
to the css. Without the option the file list will always be droppable but I doubt anyone would be unhappy about it.

**Comment by mbraak** [comment]
I pushed a new version that makes the whole files list a drop area.

* I made some changes to the styling to make it more consistent. The files div now has a border.
* The `supportDropArea` is on by default.

**Comment by BoPeng** [comment]
Thanks! I just tested it and the droparea works perfectly.

**Pull request merged**
